### ISSUE TITLE
Vivaldi history not obtained?

### ISSUE THREAD

**Issue by PAK90** [MyOutDeskLLC/node-browser-history#12]
I tried using this package with the Vivaldi browser call (`getVivaldiHistory(1000)`) but it didn't return any history results (even though my Vivaldi has plenty of history), just an empty array, no errors. I also tried `getAllHistory(1000)` and it returned some Chrome and Firefox results, but no Vivaldi. Is there some setting I have to change in Vivaldi to have this exposed? (running win10, node v10)

**Comment by tance77** [comment]
Haven't really kept up with Vivaldi in quite some time, as its not a popular browser in my area. It probably needs an update. Feel free to open a PR or I'll get to it when I have some free time.

**EDIT**

> win10

We actually didn't implement  the windows version of this. Which is why its shows nothing :) still feel free to PR it or Ill get to it when I can.

**Comment by tance77** [comment]
Now supported on windows.
